# docker/local/docker-compose.yml

version: "3.8"

services:
  # ---------------------------------
  # database
  # ---------------------------------
  db:
    image: mysql/mysql-server:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db-data80:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - shared-network

  # ---------------------------------
  # scripts
  # ---------------------------------
  scripts:
    restart: "no"
    tty: true
    build:
      context: ../../
      dockerfile: ./docker/local/scripts/nodejs/Dockerfile
    env_file:
      - ../../apps/scripts/.env
    volumes:
      - ../../apps/scripts:/project/apps/scripts
      - ../../packages:/project/packages
      - ../../package.json:/project/package.json
      - ../../package-lock.json:/project/package-lock.json
      - /project/node_modules
    working_dir: /project
    networks:
      - shared-network
    depends_on:
      - db

  # ---------------------------------
  # user_front
  # ---------------------------------
  user_front:
    restart: "no"
    tty: true
    build:
      context: ../../
      dockerfile: ./docker/local/user_front/nodejs/Dockerfile
    env_file:
      - ../../apps/user_front/.env
    ports:
      - "3001:3001"

    volumes:
      - ../../apps/user_front:/project/apps/user_front
      - ../../packages:/project/packages
      - ../../package.json:/project/package.json
      - ../../package-lock.json:/project/package-lock.json
      - /project/node_modules
    working_dir: /project
    networks:
      - shared-network
    depends_on:
      - db

volumes:
  db-data80:

networks:
  shared-network:
    name: ${PROJECT_NAME}-network
